/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Unified async database endpoint: MySQL wire (mysql_async pooled) or
//! Postgres (tokio-postgres with a small internal async pool).
//!
//! Statements are generated by [`crate::dialect`] with the right
//! placeholder style; this layer only binds values and decodes rows.

use std::sync::Arc;

use mysql_async::prelude::Queryable;
use tokio::sync::{Mutex, Semaphore};

use crate::dialect::JdbcDialectKind;
use crate::url::JdbcUrl;
use crate::value::{SqlValue, mysql_value_to_sql};

/// Query result: column names + rows of driver-neutral values.
#[derive(Debug, Clone)]
pub struct QueryResult {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<SqlValue>>,
}

impl QueryResult {
    pub fn scalar_i64(&self) -> Option<i64> {
        let row = self.rows.first()?;
        match row.first()? {
            SqlValue::Int(v) => Some(*v),
            SqlValue::UInt(v) => Some(*v as i64),
            SqlValue::Str(s) => s.parse().ok(),
            SqlValue::Float(f) => Some(*f as i64),
            _ => None,
        }
    }

    pub fn scalar_string(&self) -> Option<String> {
        let row = self.rows.first()?;
        match row.first()? {
            SqlValue::Str(s) => Some(s.clone()),
            SqlValue::Bytes(b) => Some(String::from_utf8_lossy(b).to_string()),
            other => other.as_text(),
        }
    }
}

// ---------------------------------------------------------------------------
// Postgres pool
// ---------------------------------------------------------------------------

struct PgPoolInner {
    config: tokio_postgres::Config,
    idle_tx: tokio::sync::mpsc::UnboundedSender<tokio_postgres::Client>,
    idle_rx: Mutex<tokio::sync::mpsc::UnboundedReceiver<tokio_postgres::Client>>,
    permits: Semaphore,
}

/// A small async Postgres connection pool (mirrors mysql_async's `Pool`
/// behavior: bounded concurrency, idle connections returned on drop).
#[derive(Clone)]
pub struct PgPool {
    inner: Arc<PgPoolInner>,
}

struct PgClientGuard {
    client: Option<tokio_postgres::Client>,
    pool: Arc<PgPoolInner>,
}

impl std::ops::Deref for PgClientGuard {
    type Target = tokio_postgres::Client;
    fn deref(&self) -> &Self::Target {
        self.client.as_ref().expect("client present until drop")
    }
}

impl Drop for PgClientGuard {
    fn drop(&mut self) {
        if let Some(client) = self.client.take() {
            if !client.is_closed() {
                let _ = self.pool.idle_tx.send(client);
            }
        }
    }
}

impl PgPool {
    pub fn new(config: tokio_postgres::Config, max_size: usize) -> Self {
        let (tx, rx) = tokio::sync::mpsc::unbounded_channel();
        PgPool {
            inner: Arc::new(PgPoolInner {
                config,
                idle_tx: tx,
                idle_rx: Mutex::new(rx),
                permits: Semaphore::new(max_size.max(1)),
            }),
        }
    }

    async fn get(&self) -> anyhow::Result<PgClientGuard> {
        let _permit = self.inner.permits.acquire().await?;
        if let Some(client) = self.inner.idle_rx.lock().await.recv().await {
            if !client.is_closed() {
                return Ok(PgClientGuard {
                    client: Some(client),
                    pool: self.inner.clone(),
                });
            }
        }
        let (client, connection) = self
            .inner
            .config
            .connect(tokio_postgres::NoTls)
            .await
            .map_err(|e| anyhow::anyhow!("postgres connect: {}", e))?;
        // Drive the connection; when it ends the client is marked closed.
        tokio::spawn(async move {
            if let Err(e) = connection.await {
                tracing::debug!("postgres connection ended: {}", e);
            }
        });
        Ok(PgClientGuard {
            client: Some(client),
            pool: self.inner.clone(),
        })
    }
}

/// Postgres parameter binding: text for most values (placeholders cast
/// explicitly), native bool / bytes. The binary wire formats are written
/// directly so the value kind never has to match the parameter type
/// declared by the statement.
#[derive(Debug)]
enum PgParam {
    Null,
    Bool(bool),
    Bytes(Vec<u8>),
    Text(String),
}

impl tokio_postgres::types::ToSql for PgParam {
    fn to_sql(
        &self,
        _ty: &tokio_postgres::types::Type,
        out: &mut tokio_postgres::types::private::BytesMut,
    ) -> Result<tokio_postgres::types::IsNull, Box<dyn std::error::Error + Sync + Send>> {
        use tokio_postgres::types::IsNull;
        match self {
            PgParam::Null => Ok(IsNull::Yes),
            PgParam::Bool(b) => {
                out.extend_from_slice(&[u8::from(*b)]);
                Ok(IsNull::No)
            }
            PgParam::Bytes(b) => {
                out.extend_from_slice(&(b.len() as i32).to_be_bytes());
                out.extend_from_slice(b);
                Ok(IsNull::No)
            }
            PgParam::Text(s) => {
                out.extend_from_slice(&(s.len() as i32).to_be_bytes());
                out.extend_from_slice(s.as_bytes());
                Ok(IsNull::No)
            }
        }
    }

    fn accepts(_ty: &tokio_postgres::types::Type) -> bool {
        true
    }

    tokio_postgres::types::to_sql_checked!();
}

fn pg_params(params: &[SqlValue]) -> Vec<PgParam> {
    params
        .iter()
        .map(|p| match p {
            SqlValue::Null => PgParam::Null,
            SqlValue::Bool(b) => PgParam::Bool(*b),
            SqlValue::Bytes(b) => PgParam::Bytes(b.clone()),
            other => match other.as_text() {
                Some(text) => PgParam::Text(text),
                None => PgParam::Null,
            },
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Unified endpoint
// ---------------------------------------------------------------------------

/// A pooled async connection endpoint for one database.
#[derive(Clone)]
pub enum DbEndpoint {
    MySql(mysql_async::Pool),
    Postgres(PgPool),
}

impl DbEndpoint {
    /// Connect using the given URL and credentials, verifying the
    /// connection with a trivial query.
    pub async fn connect(
        url: &JdbcUrl,
        username: &str,
        password: &str,
        pool_size: usize,
    ) -> anyhow::Result<Self> {
        match url.dialect {
            JdbcDialectKind::Postgres => {
                let mut config = tokio_postgres::Config::new();
                config
                    .host(&url.host)
                    .port(url.port)
                    .user(username)
                    .password(password);
                if !url.database.is_empty() {
                    config.dbname(&url.database);
                }
                let pool = PgPool::new(config, pool_size);
                let guard = pool.get().await?;
                guard.simple_query("SELECT 1").await?;
                drop(guard);
                Ok(DbEndpoint::Postgres(pool))
            }
            JdbcDialectKind::MySql | JdbcDialectKind::TiDB => {
                let opts = mysql_async::OptsBuilder::default()
                    .ip_or_hostname(&url.host)
                    .tcp_port(url.port)
                    .user(Some(username))
                    .pass(Some(password))
                    .db_name(if url.database.is_empty() {
                        None
                    } else {
                        Some(url.database.as_str())
                    })
                    .pool_opts(
                        mysql_async::PoolOpts::new().with_constraints(
                            mysql_async::PoolConstraints::new(1, pool_size.max(1))
                                .ok_or_else(|| anyhow::anyhow!("invalid pool constraints"))?,
                        ),
                    );
                let pool = mysql_async::Pool::new(opts);
                let mut conn = pool.get_conn().await?;
                let _: Option<i32> = conn.query_first("SELECT 1").await?;
                drop(conn);
                Ok(DbEndpoint::MySql(pool))
            }
        }
    }

    /// Execute a statement that returns no rows; returns affected rows.
    pub async fn exec(&self, sql: &str, params: &[SqlValue]) -> anyhow::Result<u64> {
        match self {
            DbEndpoint::MySql(pool) => {
                let mut conn = pool.get_conn().await?;
                let values: Vec<mysql_async::Value> = params.iter().map(|p| p.into()).collect();
                conn.exec_drop(sql, values).await?;
                Ok(0)
            }
            DbEndpoint::Postgres(pool) => {
                let client = pool.get().await?;
                let pg_params = pg_params(params);
                let refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = pg_params
                    .iter()
                    .map(|p| p as &(dyn tokio_postgres::types::ToSql + Sync))
                    .collect();
                let rows = client.execute(sql, &refs).await?;
                Ok(rows)
            }
        }
    }

    /// Execute a statement that may return no rows without failing the
    /// task when it errors (used for best-effort DDL).
    pub async fn exec_best_effort(&self, sql: &str) -> anyhow::Result<()> {
        match self {
            DbEndpoint::MySql(pool) => {
                let mut conn = pool.get_conn().await?;
                conn.query_drop(sql).await?;
            }
            DbEndpoint::Postgres(pool) => {
                let client = pool.get().await?;
                client.batch_execute(sql).await?;
            }
        }
        Ok(())
    }

    /// Run a query and decode all rows.
    pub async fn query(&self, sql: &str, params: &[SqlValue]) -> anyhow::Result<QueryResult> {
        match self {
            DbEndpoint::MySql(pool) => {
                let mut conn = pool.get_conn().await?;
                let values: Vec<mysql_async::Value> = params.iter().map(|p| p.into()).collect();
                let result: Vec<mysql_async::Row> = conn.exec(sql, values).await?;
                let columns = result
                    .first()
                    .map(|r| {
                        r.columns_ref()
                            .iter()
                            .map(|c| c.name_str().to_string())
                            .collect()
                    })
                    .unwrap_or_default();
                let rows = result
                    .iter()
                    .map(|r| {
                        (0..r.len())
                            .map(|i| {
                                mysql_value_to_sql(
                                    &r.get::<mysql_async::Value, usize>(i)
                                        .unwrap_or(mysql_async::Value::NULL),
                                )
                            })
                            .collect()
                    })
                    .collect();
                Ok(QueryResult { columns, rows })
            }
            DbEndpoint::Postgres(pool) => {
                let client = pool.get().await?;
                let pg_params = pg_params(params);
                let refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = pg_params
                    .iter()
                    .map(|p| p as &(dyn tokio_postgres::types::ToSql + Sync))
                    .collect();
                let rows = client.query(sql, &refs).await?;
                let columns = rows
                    .first()
                    .map(|r| r.columns().iter().map(|c| c.name().to_string()).collect())
                    .unwrap_or_default();
                let mut out = Vec::with_capacity(rows.len());
                for row in &rows {
                    let mut vals = Vec::with_capacity(row.len());
                    for (i, col) in row.columns().iter().enumerate() {
                        vals.push(pg_cell_to_sql(row, i, col.type_()));
                    }
                    out.push(vals);
                }
                drop(client);
                Ok(QueryResult { columns, rows: out })
            }
        }
    }
}

/// Decode a Postgres cell into a driver-neutral value using the column's
/// OID type. Temporal / numeric / json / array types come back as text
/// (sources cast them to text in the SELECT when needed).
fn pg_cell_to_sql(
    row: &tokio_postgres::Row,
    idx: usize,
    ty: &tokio_postgres::types::Type,
) -> SqlValue {
    use tokio_postgres::types::Type;
    match *ty {
        Type::BOOL => row
            .try_get::<_, Option<bool>>(idx)
            .ok()
            .flatten()
            .map(SqlValue::Bool),
        Type::INT2 => row
            .try_get::<_, Option<i16>>(idx)
            .ok()
            .flatten()
            .map(|v| SqlValue::Int(v as i64)),
        Type::INT4 => row
            .try_get::<_, Option<i32>>(idx)
            .ok()
            .flatten()
            .map(|v| SqlValue::Int(v as i64)),
        Type::INT8 => row
            .try_get::<_, Option<i64>>(idx)
            .ok()
            .flatten()
            .map(SqlValue::Int),
        Type::FLOAT4 => row
            .try_get::<_, Option<f32>>(idx)
            .ok()
            .flatten()
            .map(|v| SqlValue::Float(v as f64)),
        Type::FLOAT8 => row
            .try_get::<_, Option<f64>>(idx)
            .ok()
            .flatten()
            .map(SqlValue::Float),
        Type::BYTEA => row
            .try_get::<_, Option<Vec<u8>>>(idx)
            .ok()
            .flatten()
            .map(SqlValue::Bytes),
        _ => None,
    }
    .unwrap_or(SqlValue::Null)
}
