[package]
name = "seatunnel-engine-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Apache SeaTunnel Rust - Engine Server: Master + Worker nodes"

[dependencies]
seatunnel-engine-core = { path = "../seatunnel-engine-core" }
seatunnel-engine-comm = { path = "../seatunnel-engine-comm" }
tokio = { workspace = true }
tonic = { workspace = true }
tokio-stream = "0.1"
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
parking_lot = { workspace = true }
rust-rocksdb = { workspace = true, optional = true }
prometheus = { workspace = true, optional = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
object_store = { workspace = true }
seatunnel-api = { path = "../../seatunnel-api" }
async-trait.workspace = true

pin-project = "1"
uuid = { workspace = true }
seatunnel-engine-client = { path = "../seatunnel-engine-client" }
seatunnel-connector-cdc-mysql = { path = "../../seatunnel-connectors/seatunnel-connector-cdc-mysql", optional = true }
seatunnel-connector-cdc-postgres = { path = "../../seatunnel-connectors/seatunnel-connector-cdc-postgres", optional = true }
seatunnel-connector-cdc-tidb = { path = "../../seatunnel-connectors/seatunnel-connector-cdc-tidb", optional = true }
seatunnel-connector-jdbc = { path = "../../seatunnel-connectors/seatunnel-connector-jdbc", optional = true }
seatunnel-connector-kafka = { path = "../../seatunnel-connectors/seatunnel-connector-kafka", optional = true }
seatunnel-formats = { path = "../../seatunnel-formats", optional = true }

seatunnel-connector-common = { path = "../../seatunnel-connectors/seatunnel-connector-common" }
openraft = { version = "0.9", features = ["serde", "storage-v2", "generic-snapshot-data"] }

[features]
default = ["connectors"]
connectors = ["seatunnel-connector-cdc-mysql", "seatunnel-connector-cdc-postgres", "seatunnel-connector-cdc-tidb", "seatunnel-connector-jdbc", "seatunnel-connector-kafka", "seatunnel-formats"]
