//! Generated kvproto types from vendored .proto files.
//!
//! The .rs files are generated by `build.rs` (tonic-build + prost-build)
//! into OUT_DIR and included here.

pub mod autoid {
    include!(concat!(env!("OUT_DIR"), "/autoid.rs"));
}
pub mod backup {
    include!(concat!(env!("OUT_DIR"), "/backup.rs"));
}
pub mod cdcpb {
    include!(concat!(env!("OUT_DIR"), "/cdcpb.rs"));
}
pub mod configpb {
    include!(concat!(env!("OUT_DIR"), "/configpb.rs"));
}
pub mod coprocessor {
    include!(concat!(env!("OUT_DIR"), "/coprocessor.rs"));
}
pub mod deadlock {
    include!(concat!(env!("OUT_DIR"), "/deadlock.rs"));
}
pub mod debugpb {
    include!(concat!(env!("OUT_DIR"), "/debugpb.rs"));
}
pub mod disaggregated {
    include!(concat!(env!("OUT_DIR"), "/disaggregated.rs"));
}
pub mod disk_usage {
    include!(concat!(env!("OUT_DIR"), "/disk_usage.rs"));
}
pub mod encryptionpb {
    include!(concat!(env!("OUT_DIR"), "/encryptionpb.rs"));
}
pub mod enginepb {
    include!(concat!(env!("OUT_DIR"), "/enginepb.rs"));
}
pub mod eraftpb {
    include!(concat!(env!("OUT_DIR"), "/eraftpb.rs"));
}
pub mod errorpb {
    include!(concat!(env!("OUT_DIR"), "/errorpb.rs"));
}
pub mod gcpb {
    include!(concat!(env!("OUT_DIR"), "/gcpb.rs"));
}
pub mod import_kvpb {
    include!(concat!(env!("OUT_DIR"), "/import_kvpb.rs"));
}
pub mod import_sstpb {
    include!(concat!(env!("OUT_DIR"), "/import_sstpb.rs"));
}
pub mod keyspacepb {
    include!(concat!(env!("OUT_DIR"), "/keyspacepb.rs"));
}
pub mod kvrpcpb {
    include!(concat!(env!("OUT_DIR"), "/kvrpcpb.rs"));
}
pub mod logbackup {
    include!(concat!(env!("OUT_DIR"), "/logbackup.rs"));
}
pub mod meta_storagepb {
    include!(concat!(env!("OUT_DIR"), "/meta_storagepb.rs"));
}
pub mod metapb {
    include!(concat!(env!("OUT_DIR"), "/metapb.rs"));
}
pub mod mpp {
    include!(concat!(env!("OUT_DIR"), "/mpp.rs"));
}
pub mod pdpb {
    include!(concat!(env!("OUT_DIR"), "/pdpb.rs"));
}
pub mod raft_cmdpb {
    include!(concat!(env!("OUT_DIR"), "/raft_cmdpb.rs"));
}
pub mod raft_serverpb {
    include!(concat!(env!("OUT_DIR"), "/raft_serverpb.rs"));
}
pub mod recover_data {
    include!(concat!(env!("OUT_DIR"), "/recover_data.rs"));
}
pub mod replication_modepb {
    include!(concat!(env!("OUT_DIR"), "/replication_modepb.rs"));
}
pub mod resource_manager {
    include!(concat!(env!("OUT_DIR"), "/resource_manager.rs"));
}
pub mod resource_usage_agent {
    include!(concat!(env!("OUT_DIR"), "/resource_usage_agent.rs"));
}
pub mod schedulingpb {
    include!(concat!(env!("OUT_DIR"), "/schedulingpb.rs"));
}
pub mod tikvpb {
    include!(concat!(env!("OUT_DIR"), "/tikvpb.rs"));
}
pub mod tracepb {
    include!(concat!(env!("OUT_DIR"), "/tracepb.rs"));
}
pub mod tsopb {
    include!(concat!(env!("OUT_DIR"), "/tsopb.rs"));
}