#!/usr/bin/env bash
# Three-node symmetric hybrid pseudo-cluster on one machine: every process
# is a Raft voter (coordinator candidate) + worker executor — the
# recommended HA topology in miniature. Leader failover takes ~2s (one election round) and the
# tasks of a dead node are re-claimed by the survivors.
#
# Usage:
#   ./scripts/start-hybrid-cluster.sh    # build (debug) + run, Ctrl+C stops all
#
# Ctrl+C stops every node; per-node state dirs are KEPT under STATE_BASE so
# the cluster can be restarted without losing checkpoint history.
#
# Env:
#   NODE_PORTS   comma-separated voter ports (default 5800,5810,5820);
#                any odd count >= 3 works — two voters can never reach
#                majority, the engine rejects them at startup
#   STATE_BASE   durable state base      (default .seatunnel-state/hybrid-cluster)
#   BIN_DIR      binary directory        (default ./target/debug)
#   NO_BUILD     set to 1 to skip cargo build
#
# Cross-node checkpoint restore uses storage type "master" (replicated to
# the voters via the coordinator state snapshot) so a task moved to another
# node after a kill resumes instead of restarting from scratch — no MinIO
# required. Switch to storage.type s3 for large production checkpoints.
set -euo pipefail
cd "$(dirname "$0")/.."

IFS=',' read -r -a PORTS <<< "${NODE_PORTS:-5800,5810,5820}"
N=${#PORTS[@]}
if [ "$N" -lt 3 ] || [ $((N % 2)) -eq 0 ]; then
  echo "error: NODE_PORTS must list an odd count >= 3 of voters (got $N)" >&2
  exit 1
fi
STATE_BASE=${STATE_BASE:-.seatunnel-state/hybrid-cluster}
BIN_DIR=${BIN_DIR:-./target/debug}

port_open() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

for port in "${PORTS[@]}"; do
  if port_open "$port"; then
    echo "error: port $port already in use — stop the old instance or set NODE_PORTS" >&2
    exit 1
  fi
done

if [[ "${NO_BUILD:-0}" != "1" ]]; then
  echo "==> building engine server + CLI (debug; NO_BUILD=1 + BIN_DIR to override)"
  cargo build -p seatunnel-engine-server -p seatunnel-cli
fi
for bin in seatunnel-engine-server seatunnel; do
  [[ -x "$BIN_DIR/$bin" ]] || { echo "error: $BIN_DIR/$bin not found — build first or set BIN_DIR" >&2; exit 1; }
done

mkdir -p "$STATE_BASE"

# Shared engine config: the ordered member-list IS the Raft voter set
# (voter id = position in the list).
MEMBERS=""
for port in "${PORTS[@]}"; do
  MEMBERS+="${MEMBERS:+, }\"127.0.0.1:$port\""
done
cat > "$STATE_BASE/engine.yaml" <<EOF
# Generated by scripts/start-hybrid-cluster.sh — shared by all local nodes.
hazelcast:
  cluster-name: seatunnel-hybrid-cluster
  network:
    join:
      tcp-ip:
        enabled: true
        member-list: [$MEMBERS]
seatunnel:
  engine:
    # Faster liveness than the 30s/60s defaults so a killed node's tasks
    # are re-claimed within seconds — good for a local demo, restore the
    # defaults (30s/60s) for production.
    worker-soft-timeout-ms: 5000
    worker-timeout-ms: 10000
    checkpoint:
      storage:
        # Shared backend: a task re-claimed by another node after a kill
        # restores from here instead of restarting the pipeline.
        type: master
EOF

PIDS=()
cleanup() {
  echo
  echo "==> stopping $N hybrid node(s) (state kept in $STATE_BASE)"
  for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done
}
trap cleanup EXIT

IDX=0
for port in "${PORTS[@]}"; do
  IDX=$((IDX + 1))
  NODE_DIR="$STATE_BASE/node-$IDX"
  mkdir -p "$NODE_DIR"
  echo "==> starting hybrid node $IDX on 127.0.0.1:$port (log: $NODE_DIR/server.log)"
  RUST_LOG=${RUST_LOG:-info} "$BIN_DIR/seatunnel-engine-server" --role hybrid \
    --addr "127.0.0.1:$port" --advertise-addr "127.0.0.1:$port" \
    --worker-id "hybrid-$IDX" --state-dir "$NODE_DIR" \
    --config "$STATE_BASE/engine.yaml" >"$NODE_DIR/server.log" 2>&1 &
  PIDS+=($!)
  sleep 1
done

# Wait for Raft to elect a leader (fast election: 1-3s after a majority is
# up, but allow margin for slow machines).
LEADER=""
for _ in $(seq 1 30); do
  for i in "${!PORTS[@]}"; do
    CLUSTER=$("$BIN_DIR/seatunnel" cluster -a "127.0.0.1:${PORTS[$i]}" 2>/dev/null || true)
    if [ -n "$CLUSTER" ] && echo "$CLUSTER" | grep -q "Cluster leader" \
       && ! echo "$CLUSTER" | grep -q "Cluster leader   : -"; then
      LEADER=$(echo "$CLUSTER" | sed -n '1,2p' | sed 's/^/  /')
      break 2
    fi
  done
  sleep 1
done
[ -n "$LEADER" ] || {
  echo "error: no leader elected in 30s — tails of the node logs:" >&2
  for IDX in $(seq 1 "$N"); do
    echo "--- $STATE_BASE/node-$IDX/server.log ---" >&2
    tail -10 "$STATE_BASE/node-$IDX/server.log" >&2
  done
  exit 1
}

echo
echo "=================================================================="
echo "  $N-node hybrid pseudo-cluster is up (one process = voter + worker)"
echo "$LEADER"
i=0
for port in "${PORTS[@]}"; do
  echo "  node-$((i + 1))  127.0.0.1:$port  pid ${PIDS[$i]}  log $STATE_BASE/node-$((i + 1))/server.log"
  i=$((i + 1))
done
FIRST="127.0.0.1:${PORTS[0]}"
echo "  Submit a job   : $BIN_DIR/seatunnel job submit -c <job.yaml> -a $FIRST"
echo "  Cluster status : $BIN_DIR/seatunnel cluster -a $FIRST   (any node works)"
echo "  Try failover   : kill -9 one of the pids above — a new leader is"
echo "                   elected in ~2s. NOTE: task re-claim across a node"
echo "                   death is still racy (see docs/en/cluster-ha-design.md"
echo "                   known limitations); resubmit the job if it stalls."
echo "  Ctrl+C stops all nodes; state in $STATE_BASE is kept."
echo "=================================================================="
wait
