-- Post-benchmark cleanup: drop the benchmark databases entirely and
-- shrink the binary log (the load test generates millions of ROW
-- events). Only touches objects created by init_bench_schema.sql.
DROP DATABASE IF EXISTS neworiental_v3;
DROP DATABASE IF EXISTS neworiental_user;
DROP DATABASE IF EXISTS neworiental_product;
DROP DATABASE IF EXISTS ailearn_okminicourse;
DROP DATABASE IF EXISTS `ailearn-english`;
DROP DATABASE IF EXISTS neworiental_data_recommand;
DROP DATABASE IF EXISTS ailearn_kefu;
-- Purge the binary log generated by the load test (millions of ROW
-- events). MySQL 8.0 spells it RESET MASTER; 8.4+ renamed it to
-- RESET BINARY LOGS AND GTIDS.
RESET MASTER;
